env:
  global:
    - LC_CTYPE=en_US.UTF-8
matrix:
  include:
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      before_install:
        - carthage checkout
      script:
      # Restore pod build before shipping for 3.0
      # - pod lib lint
      # Generate xcodeprojects for the pure Swift PM deps
        - (cd Carthage/Checkouts/Operadics && xcrun swift package generate-xcodeproj --xcconfig-overrides ../../../deployments.xcconfig)
        - carthage build --no-skip-current
    - os: osx
      language: objective-c
      osx_image: xcode8.3
      before_install:
      # Generate xcodeprojects for the pure Swift PM deps
        - carthage checkout && (cd Carthage/Checkouts/Operadics && xcrun swift package generate-xcodeproj --xcconfig-overrides ../../../deployments.xcconfig)
      script:
        - set -o pipefail
        - xcodebuild test -scheme Algebra | xcpretty -c
        # !!!: Make sure desired device name & OS version are suitable for the Xcode version installed on osx_image
        - iOS_DEVICE_NAME="iPad Pro (12.9-inch)"
        - iOS_RUNTIME_VERSION="10.0"
        # Get simulator identifier for desired device/runtime pair
        - SIMULATOR_ID=$(xcrun instruments -s | grep -o "${iOS_DEVICE_NAME} (${iOS_RUNTIME_VERSION}) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/")
        - echo $SIMULATOR_ID
        - echo $iOS_DEVICE_NAME
        - echo $iOS_RUNTIME_VERSION
        - xcodebuild test -scheme Algebra-iOS -destination "platform=iOS Simulator,name=${iOS_DEVICE_NAME},OS=${iOS_RUNTIME_VERSION}" | xcpretty -c
        - xcodebuild test -scheme Algebra-tvOS -destination 'platform=tvOS Simulator,name=Apple TV 1080p' | xcpretty -c
    - os: linux
      language: generic
      sudo: required
      dist: trusty
      before_install:
        - eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)"
      script:
        - swift build
        - SWIFTPM_TEST_Algebra=YES swift test
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1d781e1bcbabade5de35
    on_success: always
    on_failure: always
    on_start: always
